Enhanced Multi-Word Search Functionality
ppetzold/nestjs-paginate pull request #1001
Opened 2024-10-12 12:01 UTC by sambhavnoobcoder

## Description
This PR introduces an enhancement to the search functionality in the paginate function, allowing for more flexible and powerful searches across multiple columns.
## Changes Made

- Modified the search logic in the paginate function to split the search query into individual words.
- Implemented a nested Brackets structure to apply each word across all searchable columns.
- Used AND conditions between different words and OR conditions between columns for each word.
- Maintained type casting for PostgreSQL and CockroachDB to ensure compatibility.

## Motivation
This change addresses a user-reported limitation where searching for multiple words or IDs in the same query was not possible. The new implementation allows for more natural search queries that can include multiple words and numeric IDs, searching across all specified columns.
## Usage Example
With this change, a search query like "John Doe 123" will match records where:

- "John" appears in any searchable column, AND
- "Doe" appears in any searchable column, AND
- "123" appears in any searchable column

This is particularly useful for scenarios where users want to search for names and IDs in the same query.

addressese issue #918

2024-10-12 12:47 UTC, Helveg commented
Thanks! Looks like a much requested and useful addition! Could you run `npm run format` so that CI continues?

Then 1 concern I have is that this is now enabled by default, with no way of keeping the strict search functionality. I think it's worth keeping both search modes available.

2024-10-12 18:32 UTC, sambhavnoobcoder commented
i've made the necessary changes . If it's all good, feel free to merge. Cheers!

2024-10-22 12:09 UTC, ppetzold requested changes
looks good to me - other than the breaking change.

let's keep strict search the default.

2024-10-22 16:25 UTC, ppetzold requested changes
also please add new conf param description to README

2024-10-22 16:25 UTC, ppetzold commented on src/paginate.ts
> +    strictSearch?: boolean // New property to control search mode
`multiWordSearch`

2024-10-23 09:18 UTC, ppetzold requested changes

2024-10-23 09:18 UTC, ppetzold commented on src/paginate.ts
> +    multiWordSearch?: boolean // New property to control multi-word search behavior
you can remove comment here. but please add description to README

2024-10-23 09:42 UTC, ppetzold approved these changes

2024-10-23 09:43 UTC, merged

2024-10-23 09:47 UTC, ppetzold commented
:tada: This PR is included in version 9.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/nestjs-paginate/v/9.2.0)
- [GitHub release](https://github.com/ppetzold/nestjs-paginate/releases/tag/v9.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-10-23 10:04 UTC, sambhavnoobcoder commented
Glad to be a part of the release . Hoping to stay around and contribute more . cheers .