Allow user to choose between limit/offset and take/skip.
ppetzold/nestjs-paginate pull request #508
Opened 2023-03-01 19:36 UTC by emulienfou

Leave the user the choice to choose between limit/offset and take/skip.
By doing so this avoid user to create a custom queryBuilder to pass to `paginate` function.

> Related to issue: https://github.com/typeorm/typeorm/issues/5670

2023-03-01 19:43 UTC, xMase commented
I suggest to insert a disclaimer in readme, because the use of limit/offset can cause this side effect.

2023-03-02 09:01 UTC, ppetzold requested changes
Otherwise LGTM 🌟

2023-03-02 09:01 UTC, ppetzold commented on src/paginate.ts
> +export enum PaginationTypeEnum {
Could you remove the `Enum` suffix? As we don't do so on other enums as well :)

2023-03-06 08:25 UTC, ppetzold approved these changes

2023-03-06 08:25 UTC, merged

2023-03-06 08:27 UTC, ppetzold commented
:tada: This PR is included in version 4.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/nestjs-paginate/v/4.13.0)
- [GitHub release](https://github.com/ppetzold/nestjs-paginate/releases/tag/v4.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: