Add `_rel` suffix to relationship columns to avoid duplicate columns
ppetzold/nestjs-paginate pull request #649
Opened 2023-06-20 08:58 UTC by Helveg

This PR attempts to address #518 by introducing a `_rel` suffix to all relationship aliases so that `parent.relationship.id` doesn't conflict with `parent.relationship_id` (a common occurence with TypeORM's default naming strategy).

I do not have enough understanding of the entire codebase to be confident that this is the optimal solution, but it shows a solution, which you should feel free to improve upon. I drafted this against the test suite, which are all passing, except for 1. Appearantly my solution makes it so that a virtual column filter is now selected in the resulting items, which was not the case before, this should be fixed but I don't know where this happens.

Also, the test suite should be extended to cover MySQL, if you draft up how you would like to extend the current 2-driver (SQLite & PostGres) setup to a generic n-driver setup, I can fix all the failing MySQL tests for you.

Let me know what you think!

2023-06-20 09:15 UTC, Helveg commented
Strange, locally the `'should return result sorted and filter by a virtual column in main entity'` fails, but here it doesn't seem to.

2023-07-12 08:44 UTC, Helveg commented
@ppetzold any traction on this?

2023-07-13 14:15 UTC, ppetzold commented
Good stuff.. a test case which demonstrate that this fixes the issue which would great ! :)

Will add a branch with mysql test runner these days

2023-07-13 14:15 UTC, ppetzold requested changes
add test case

2023-07-16 17:43 UTC, ppetzold commented
@Helveg sorry, didn't really pay attention. you cannot build a testcase as only mysql was affected 🙈 got it.

seems good then. merging.

2023-07-16 17:43 UTC, merged

2023-07-16 17:45 UTC, ppetzold commented
:tada: This PR is included in version 8.1.6 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/nestjs-paginate/v/8.1.6)
- [GitHub release](https://github.com/ppetzold/nestjs-paginate/releases/tag/v8.1.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-16 22:09 UTC, Helveg commented
Is the 1 test that this change breaks not important?

2023-07-18 07:11 UTC, ppetzold commented
seems to pass in CI. I guess it's good then noh?

2023-09-13 15:49 UTC, phDooY commented
Looks like this PR introduced something breaking

```
missing FROM-clause entry for table "tx_partner_rel"
```

I have search columns using partner entity like this:

```
searchableColumns: [
        'from',
        'to',
        'partner.name',
        'account.name'
      ],
```

Using Postgres db

2023-09-13 15:54 UTC, ppetzold commented
Hmm.. searches on many to one seem to be fine. see https://github.com/ppetzold/nestjs-paginate/blob/master/src/paginate.spec.ts#L583

ci runs against sqlite and postgres.

any chance you build a test case which reproduces the error?

2023-09-13 16:15 UTC, phDooY commented
Thanks will take a look. I will try to build a test case the following week, maybe an edge case of how we are using createQueryBuilder