WIP: #517 error
ppetzold/nestjs-paginate pull request #857
Opened 2024-01-15 09:53 UTC by gylove1994

Related: #517

2024-01-16 08:49 UTC, ppetzold requested changes
could you use the existing entities or enhance the existing entities to showcase the error?

that way this branch can directly be used to implement the bug fix as well

2024-01-16 13:17 UTC, gylove1994 commented
> could you use the existing entities or enhance the existing entities to showcase the error?
> 
> that way this branch can directly be used to implement the bug fix as well

Seem using the existing entities is hard to reproduce this error. So I removed some redundant code to make it more clear.

2024-01-21 03:10 UTC, gylove1994 commented
any progress?

2024-01-21 04:55 UTC, vsamofal commented
> any progress?

@gylove1994 

could you please fix lint issues

as for me changes looks ok

2024-03-03 18:46 UTC, Helveg commented
Hi @gylove1994 ! If you change this test to use the existing entities I can have a look for you :) Why exactly is it easier to use these new entities? Maybe if I understand that, I can find a good middle ground :)

2025-03-28 01:54 UTC, closed without merging