FIX: sort by subquery results in error that tableAlias.column does not exists
ppetzold/nestjs-paginate pull request #909
Opened 2024-04-29 14:45 UTC by MohdAhmad1

…t exists

2024-04-30 12:07 UTC, MrSharpp approved these changes

2024-04-30 12:08 UTC, MrSharpp approved these changes

2024-04-30 15:48 UTC, Helveg commented
Hi! Thanks for your contribution! Could you add a test that shows that this PR fixes the problem you speak of? :)

2024-05-02 17:39 UTC, ppetzold requested changes
Please see comment from @Helveg 
> Hi! Thanks for your contribution! Could you add a test that shows that this PR fixes the problem you speak of? :)

If you have showcased / covered the bug in a test, I am happily merging your PR 👋 

EDIT: CI is failing due to format. Run `npm run format` to fix.

2024-09-30 13:59 UTC, closed without merging